plugins {
	id 'java'												// Java 컴파일러 플러그인
	id 'org.springframework.boot' version '3.2.9'			// Spring Boot 플러그인 (3.2.9)
	id 'io.spring.dependency-management' version '1.1.7' 	// Spring 의존성 관리 플러그인 (1.1.7)
}

group = 'com.phaethon'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		// Java 17을 사용하도록 설정
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral() // Maven 중앙 저장소에서 의존성 다운로드
}

dependencies {
	// Spring Boot의 기본 스타터 의존성
	implementation 'org.springframework.boot:spring-boot-starter'			// Spring Boot 기본 스타터
	implementation 'org.springframework.boot:spring-boot-starter-web'		// 웹 개발 스타터
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'	// JPA 스타터
	testImplementation 'org.springframework.boot:spring-boot-starter-test'	// Spring Boot 테스트 스타터

	// SQLite 의존성
	implementation 'org.xerial:sqlite-jdbc:3.45.1.0'								// SQLite JDBC 드라이버
	implementation 'org.hibernate.orm:hibernate-community-dialects:6.4.2.Final'		// Hibernate Community Dialects
	runtimeOnly 'org.xerial:sqlite-jdbc:3.45.1.0'									// SQLite JDBC 드라이버를 런타임에만 포함

	// Lombok 의존성 (코드 자동 생성, getter/setter 등)
	compileOnly("org.projectlombok:lombok:1.18.30")			// 컴파일 시 Lombok 사용 (실행 시에는 필요 없음)
	annotationProcessor("org.projectlombok:lombok:1.18.30") // Lombok 애너테이션 프로세서 활성화
}

tasks.named('test') {
	useJUnitPlatform()
}

// Spring Boot 애플리케이션은 기본적으로 실행 가능한 JAR 파일을 생성한다. 클라우드 타입에서 빌드를 쉽게 하기 위해, JAR 파일 빌드를 비활성화 
jar {
	enabled = false
}
