# 애플리케이션 이름 설정
spring.application.name=pharmesan

# 서버 주소, 포트 설정
server.address=0.0.0.0 # 서버가 모든 네트워크 인터페이스에서 접근 가능하도록 설정
server.port=8080

# 데이터베이스 연결 설정 (SQLite)
spring.datasource.url=jdbc:sqlite:./db.sqlite			# SQLite 데이터베이스 파일 경로 설정.
spring.datasource.driver-class-name=org.sqlite.JDBC		# SQLite JDBC 드라이버 클래스 지정

# JPA와 Hibernate 설정
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect	# Hibernate가 사용할 SQLite 다이얼렉트를 지정
spring.jpa.hibernate.ddl-auto=update										# Hibernate가 데이터베이스 스키마를 자동으로 업데이트하도록 설정
spring.jpa.show-sql=true													# Hibernate가 실행한 SQL을 콘솔에 출력하도록 설정